/**
 * Generates work/<slug>.html with the case content inlined.
 *
 * Runs before `vite dev` and `vite build` (see the npm pre-scripts), so the
 * pages on disk always match src/case/cases.js. The browser bundle no longer
 * renders any text — it only attaches interactive behaviour to markup that is
 * already there.
 *
 * Image URLs are written as paths relative to work/, which Vite picks up from
 * the HTML entry and rewrites to hashed asset URLs at build time.
 */

import { readdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve as resolvePath, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CASES } from '../src/case/cases.js';
import { renderCaseHtml } from '../src/case/renderHtml.js';

const root = resolvePath(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Map every image in a case's folder by basename, so the data can name
 * "01-main.png" and still resolve after the file was re-encoded as .jpg.
 */
function imageIndex(slug) {
  const dir = resolvePath(root, 'src/images', slug);
  if (!existsSync(dir)) return new Map();
  return new Map(readdirSync(dir).map((f) => [f.replace(/\.[^.]+$/, ''), f]));
}

const missing = [];

function makeResolver(slug) {
  const index = imageIndex(slug);
  return (_slug, file) => {
    const base = String(file).replace(/\.[^.]+$/, '');
    const found = index.get(base);
    if (!found) {
      missing.push(`${slug}/${file}`);
      return null;
    }
    return `../src/images/${slug}/${found}`;
  };
}

const page = (c, content) => `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <title>${c.title} — Gabriel Ganzarolli</title>
    <meta name="description" content="${c.headline}" />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;800&display=swap"
      rel="stylesheet"
    />
  </head>

  <!-- GENERATED by scripts/build-cases.mjs from src/case/cases.js.
       Edit the case data, not this file. -->
  <body data-case="${c.slug}">
    <nav class="case-nav">
      <a class="home" href="../index.html">Gabriel Ganzarolli</a>
      <a href="../index.html#work">All work</a>
    </nav>

    <div id="case">${content}</div>

    <footer class="case-foot">
      <p>Gabriel Ganzarolli — São Paulo</p>
      <a href="../index.html">Back to the work</a>
    </footer>

    <script type="module" src="/src/case/main.js"></script>
  </body>
</html>
`;

let written = 0;
for (const c of CASES) {
  const content = renderCaseHtml(c, makeResolver(c.slug));
  writeFileSync(resolvePath(root, 'work', `${c.slug}.html`), page(c, content), 'utf8');
  written++;
}

console.log(`build-cases: wrote ${written} page(s)`);
if (missing.length) {
  console.log(`build-cases: ${missing.length} image(s) not found:\n  ${missing.join('\n  ')}`);
}
